.\" Manpage for atom-packages
.\" Contact kikefontanlorenzo@gmail.com to correct errors or typos.

.\" -------------------REFERENCES------------------
.\" http://www.linuxhowtos.org/System/creatingman.htm
.\" https://www.cyberciti.biz/faq/linux-unix-creating-a-manpage/

.\" --------------------SECTION--------------------

.TH man 1 "24 Dec 2018" "1.0" "atom-packages man page"

.\" --------------------SECTION--------------------

.SH NAME
.PP
atom-packages \- install the selection of @CosasDePuma Atom packages.

.\" --------------------SECTION--------------------

.SH SYNOPSIS
.PP
atom-packages
[OPTION]
.PP
atom-packages
[PACKAGE]

.\" --------------------SECTION--------------------

.SH DESCRIPTION
.PP
atom-packages
is a custom installer to configure your computer with the Atom packages selection of @CosasDePuma.
.PP
With no PACKAGE or no OPTION, shows a dialog menu.
.TP
.B -a, --all
install all the available packages

.\" --------------------SECTION--------------------

.SH EXAMPLES
.PP
.IP atom-packages
Show a dialog menu.
.PP
.IP atom-packages --all
Install all the available packages.
.PP
.IP atom-packages file-icons platformio-ide-terminal
Only install File-Icons and PlatformIO-IDE-Terminal

.\" --------------------SECTION--------------------

.SH BUGS

No known bugs.

.\" --------------------SECTION--------------------

.SH REPORTING BUGS

GitHub issues page:
.I https://github.com/cosasdepuma/setup/issues

.\" --------------------SECTION--------------------

.SH AUTHOR

Written by Kike Fontán (@CosasDePuma) <kikefontanlorenzo@gmail.com>
