.\" Manpage for dockerfunc-aliases
.\" Contact kikefontanlorenzo@gmail.com to correct errors or typos.

.\" -------------------REFERENCES------------------
.\" http://www.linuxhowtos.org/System/creatingman.htm
.\" https://www.cyberciti.biz/faq/linux-unix-creating-a-manpage/

.\" --------------------SECTION--------------------

.TH man 1 "24 Dec 2018" "1.0" "dockerfunc-aliases man page"

.\" --------------------SECTION--------------------

.SH NAME
.PP
dockerfunc-aliases \- create or modify the .dockerfunc configuration file.

.\" --------------------SECTION--------------------

.SH SYNOPSIS
.PP
dockerfunc-aliases
[OPTION]
.PP
dockerfunc-aliases
[PROGRAM]

.\" --------------------SECTION--------------------

.SH DESCRIPTION
.PP
dockerfunc-aliases
is a wizard to configure your personal .dockerfunc file.
.PP
With no PROGRAM or no OPTION, shows a dialog menu.
.TP
.B -a, --all
append all the available programs

.\" --------------------SECTION--------------------

.SH EXAMPLES
.PP
.IP dockerfunc-aliases
Show a dialog menu.
.PP
.IP dockerfunc-aliases --all
Append all the available programs.
.PP
.IP dockerfunc-aliases eclipse nmap swipl
Only append Eclipse, NMap and SWIpl.

.\" --------------------SECTION--------------------

.SH BUGS

No known bugs.

.\" --------------------SECTION--------------------

.SH REPORTING BUGS

GitHub issues page:
.I https://github.com/cosasdepuma/setup/issues

.\" --------------------SECTION--------------------

.SH AUTHOR

Written by Kike Fontán (@CosasDePuma) <kikefontanlorenzo@gmail.com>
