.\" Manpage for program-bundle
.\" Contact kikefontanlorenzo@gmail.com to correct errors or typos.

.\" -------------------REFERENCES------------------
.\" http://www.linuxhowtos.org/System/creatingman.htm
.\" https://www.cyberciti.biz/faq/linux-unix-creating-a-manpage/

.\" --------------------SECTION--------------------

.TH man 8 "23 Dec 2018" "1.0" "program-bundle man page"

.\" --------------------SECTION--------------------

.SH NAME
.PP
program-bundle \- install the selection of @CosasDePuma programs.

.\" --------------------SECTION--------------------

.SH SYNOPSIS
.PP
program-bundle
[OPTION]
.PP
program-bundle
[PROGRAM]

.\" --------------------SECTION--------------------

.SH DESCRIPTION
.PP
program-bundle
is a custom installer to configure your computer with the program selection of @CosasDePuma.
.PP
With no PROGRAM or no OPTION, shows a dialog menu.
.TP
.B -a, --all
install all the available programs

.\" --------------------SECTION--------------------

.SH EXAMPLES
.PP
.IP program-bundle
Show a dialog menu.
.PP
.IP program-bundle --all
Install all the available programs.
.PP
.IP program-bundle atom haskell nodejs
Only install Atom, Haskell-Platform and NodeJS/NPM.

.\" --------------------SECTION--------------------

.SH BUGS

No known bugs.

.\" --------------------SECTION--------------------

.SH REPORTING BUGS

GitHub issues page:
.I https://github.com/cosasdepuma/setup/issues

.\" --------------------SECTION--------------------

.SH AUTHOR

Written by Kike Fontán (@CosasDePuma) <kikefontanlorenzo@gmail.com>
