.\" Manpage for vscode-extensions
.\" Contact kikefontanlorenzo@gmail.com to correct errors or typos.

.\" -------------------REFERENCES------------------
.\" http://www.linuxhowtos.org/System/creatingman.htm
.\" https://www.cyberciti.biz/faq/linux-unix-creating-a-manpage/

.\" --------------------SECTION--------------------

.TH man 1 "24 Dec 2018" "1.0" "vscode-extensions man page"

.\" --------------------SECTION--------------------

.SH NAME
.PP
vscode-extensions \- install the selection of @CosasDePuma VSCode extensions.

.\" --------------------SECTION--------------------

.SH SYNOPSIS
.PP
vscode-extensions
[OPTION]
.PP
vscode-extensions
[EXTENSION]

.\" --------------------SECTION--------------------

.SH DESCRIPTION
.PP
vscode-extensions
is a custom installer to configure your computer with the VSCode extensions selection of @CosasDePuma.
.PP
With no EXTENSION or no OPTION, shows a dialog menu.
.TP
.B -a, --all
install all the available extensions.

.\" --------------------SECTION--------------------

.SH EXAMPLES
.PP
.IP vscode-extensions
Show a dialog menu.
.PP
.IP vscode-extensions --all
Install all the available extensions.
.PP
.IP vscode-extensions python vscode-icons vscode-theme-onedark
Only install Python support, VSCode-Icons and OneDark Theme.

.\" --------------------SECTION--------------------

.SH BUGS

No known bugs.

.\" --------------------SECTION--------------------

.SH REPORTING BUGS

GitHub issues page:
.I https://github.com/cosasdepuma/setup/issues

.\" --------------------SECTION--------------------

.SH AUTHOR

Written by Kike Fontán (@CosasDePuma) <kikefontanlorenzo@gmail.com>
