name: Shellcheck

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Run Shellcheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: .bin
